//https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GHCommitState.java
// PENDING, SUCCESS, ERROR, FAILURE

properties([
  disableConcurrentBuilds(),
  parameters([
    string(name: 'REPO_REFSPEC', defaultValue: '+refs/pull/*:refs/remotes/origin/pr/*', description: 'clone refspec'),
    string(name: 'TARGET_BRANCH_NAME', defaultValue: 'refs/remotes/origin/pr/2/head', description: 'Target full ref branch name'),
    string(name: 'HEAD_SHA', defaultValue: '', description: ''),
    string(name: 'BASE_SHA', defaultValue: '', description: ''),
    string(name: 'REPO_HTML_URL', defaultValue: '', description: '')
  ]),
  pipelineTriggers([])
])


def updateGithubCommitStatus(context, state, message) {
  com.cloudbees.jenkins.GitHubRepositoryName.create(params.REPO_HTML_URL).resolve().each{ repo ->
    repo.createCommitStatus(params.HEAD_SHA, state, env.BUILD_URL, message, context)
  }
}

try{
  node('master') {
    updateGithubCommitStatus('jenkins/ci', org.kohsuke.github.GHCommitState.PENDING, 'Build in progress')
  }
  
  stage('build') {
      echo "Building..."
      echo "Something cool"
      echo "ping"
      echo "pong"
     echo "Hello"
  }
  
  node('master') {
    updateGithubCommitStatus('jenkins/ci', org.kohsuke.github.GHCommitState.SUCCESS, 'Build complete')
  }
}catch (exception) {
  updateGithubCommitStatus('jenkins/ci', org.kohsuke.github.GHCommitState.ERROR, 'Build Error')
}
